name: CI

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - '*'

jobs:
  run-tests:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache/restore@v3
        with:
          key: dependencies
          path: .build/checkouts

      - name: Build swift package
        run: swift build -v

      - name: Run tests
        run: swift test --enable-code-coverage -v

      - name: Export coverage test
        run: |
          BUILD_PATH=$(swift build --show-bin-path)
          xcrun llvm-cov report \
            "$(find $(find $BUILD_PATH -name '*.xctest') -perm +111 -type f)" \
            --instr-profile "$BUILD_PATH/codecov/default.profdata" \
            --ignore-filename-regex='.*build/checkouts.*' \
            --ignore-filename-regex='Tests/.*' > "$BUILD_PATH/codecov/lcov.info"
          echo "# Coverage Job Summary" >> $GITHUB_STEP_SUMMARY
          echo "\n" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "$(cat $BUILD_PATH/codecov/lcov.info)" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: PR comment with reactions
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
             "$(cat $GITHUB_STEP_SUMMARY)"

      - name: Cache swift packages
        uses: actions/cache/save@v3
        with:
          path: .build/checkouts
          key: dependencies
